import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app=initializeApp(firebaseConfig); const auth=getAuth(app); const db=getFirestore(app);
const SUPERADMIN="servicehpmaja@gmail.com";
const pages={
  "index.html":["Dashboard","LAPORAN & DASHBOARD"],"servisan.html":["Input Servisan","INPUT TRANSAKSI"],"penjualan.html":["Input Penjualan","INPUT TRANSAKSI"],
  "data-servis.html":["Data Servis","DATA KONTER (ISOLASI)"],"data-penjualan.html":["Data Penjualan","DATA KONTER (ISOLASI)"],"stock.html":["Stock","DATA KONTER (ISOLASI)"],"tampil-stock.html":["Tampil Stock","DATA KONTER (ISOLASI)"],
  "pengeluaran.html":["Pengeluaran","DATA KONTER (ISOLASI)"],"ringkasan-pendapatan.html":["Ringkasan Pendapatan","LAPORAN & DASHBOARD"],"dashboard-admin.html":["Dashboard Admin","SUPERADMIN ONLY"],
  "data-karyawan.html":["Data Karyawan","KARYAWAN & ABSENSI"],"absensi-karyawan.html":["Absensi Karyawan","KARYAWAN & ABSENSI"],"izin-akses.html":["Izin Akses","KARYAWAN & ABSENSI"],
  "request-saldo.html":["Request Saldo","RESELLER & SALDO"],"saldo-token.html":["Saldo Token","RESELLER & SALDO"],"token-registrasi.html":["Token Registrasi","RESELLER & SALDO"],"token-perpanjangan.html":["Token Perpanjangan","RESELLER & SALDO"],"token-reseller.html":["Token Reseller","SUPERADMIN ONLY"],
  "cek-paket.html":["Cek Paket","RESELLER & SALDO"],"daftar-pengguna.html":["Daftar Pengguna","SUPERADMIN ONLY"],"pengaturan.html":["Pengaturan","LAINNYA"],"about.html":["About","LAINNYA"],"page.html":["Halaman","LAINNYA"]
};
const menu=[
 ["INPUT TRANSAKSI",[["Input Servisan","servisan.html"],["Input Penjualan","penjualan.html"]]],
 ["DATA KONTER (ISOLASI)",[["Data Servis","data-servis.html"],["Data Penjualan","data-penjualan.html"],["Stock","stock.html"],["Tampil Stock","tampil-stock.html"],["Pengeluaran","pengeluaran.html"]]],
 ["LAPORAN & DASHBOARD",[["Dashboard","index.html"],["Ringkasan Pendapatan","ringkasan-pendapatan.html"]]],
 ["KARYAWAN & ABSENSI",[["Data Karyawan","data-karyawan.html"],["Absensi Karyawan","absensi-karyawan.html"],["Izin Akses","izin-akses.html"]]],
 ["RESELLER & SALDO",[["Request Saldo","request-saldo.html"],["Saldo Token","saldo-token.html"],["Token Registrasi","token-registrasi.html"],["Token Perpanjangan","token-perpanjangan.html"],["Cek Paket","cek-paket.html"]]],
 ["SUPERADMIN ONLY",[["Dashboard Admin","dashboard-admin.html"],["Token Reseller","token-reseller.html"],["Daftar Pengguna","daftar-pengguna.html"]]],
 ["LAINNYA",[["Pengaturan","pengaturan.html"],["About","about.html"],["Halaman","page.html"]]]
];
function $(id){return document.getElementById(id)}
function toast(msg){let x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
export async function currentUser(){if(!auth.currentUser)return null;const u=auth.currentUser;let data={uid:u.uid,email:u.email||"",displayName:u.displayName||""};try{const snap=await getDoc(doc(db,'users',u.uid));if(snap.exists())data={...data,...snap.data()}}catch(e){}if((data.email||u.email||'').toLowerCase()===SUPERADMIN)data.role='SUPERADMIN';return data}
function header(user,title){return `<header class="topbar"><img class="logo" src="logo.png" alt="FIXZY"><div class="brand"><div class="brand-title">${esc(title)}</div><div class="brand-sub">FIXZY • Isolasi data Owner aktif</div></div><div class="account"><div class="account-name">${esc(user?.displayName||user?.nama||user?.email||'Belum Login')}</div><div class="account-role">${esc((user?.role||'').toUpperCase())}</div></div><button class="icon-btn" id="refreshBtn" title="Refresh">↻</button><button class="icon-btn" id="menuBtn" title="Menu">☰</button></header>`}
function drawer(){let html='<aside class="drawer" id="drawer"><div class="drawer-head"><img src="logo.png" alt="FIXZY"><div><h3>Menu FIXZY</h3><small>Isolasi konter aktif</small></div><button class="icon-btn" id="closeMenu" style="margin-left:auto;color:#fff">×</button></div>';for(const [group,items] of menu){html+=`<div class="nav-group">${group}</div>`;for(const [name,href] of items)html+=`<a class="nav-link" href="${href}">${name}</a>`}html+='<a class="nav-link danger" href="#" id="logoutBtn">🚪 Logout</a></aside>';return html}
function shell(user,title,content){document.body.innerHTML=header(user,title)+drawer()+`<main>${content}</main><div class="footer">FIXZY • Data bisnis hanya milik Owner/Konter terkait</div>`;$("menuBtn").onclick=()=>$("drawer").classList.add('open');$("closeMenu").onclick=()=>$("drawer").classList.remove('open');$("refreshBtn").onclick=()=>location.reload();$("logoutBtn").onclick=async e=>{e.preventDefault();await signOut(auth);location.href='login.html'};}
function pageContent(file,user){const title=pages[file]?.[0]||'FIXZY';const role=(user?.role||'').toUpperCase();const owner=user?.ownerEmail||user?.email||'';if(file==='dashboard-admin.html'||file==='token-reseller.html'||file==='daftar-pengguna.html')return `<section class="card"><h1 class="page-title">${title}</h1><p class="page-sub">Area administrasi sistem.</p>${role==='SUPERADMIN'?'<div class="notice">SUPERADMIN aktif. Halaman dapat diuji, tetapi data bisnis Owner tetap tidak dicampur.</div>':'<div class="notice">Akses halaman ini hanya untuk SUPERADMIN.</div>'}</section>`;
if(file==='index.html')return `<section><h1 class="page-title">Dashboard FIXZY</h1><p class="page-sub">Owner: <b>${esc(owner)}</b></p><div class="grid"><div class="stat"><small>OMSET</small><strong>Rp 0</strong></div><div class="stat"><small>PENDAPATAN</small><strong>Rp 0</strong></div><div class="stat"><small>PIUTANG</small><strong>Rp 0</strong></div><div class="stat"><small>LABA BERSIH</small><strong>Rp 0</strong></div></div><div class="card"><div class="notice">Perhitungan dashboard nantinya membaca Firestore sesuai Owner/Konter aktif, bukan localStorage.</div></div></section>`;
if(file==='about.html')return `<section class="card"><h1 class="page-title">FIXZY</h1><p class="page-sub">Sistem bisnis teknisi dan konter.</p><div class="notice">Header FIXZY menggunakan logo.png, nama akun dari Firebase Auth/Firestore, dan tombol refresh.</div></section>`;
if(file==='pengaturan.html')return `<section class="card"><h1 class="page-title">Pengaturan</h1><p class="page-sub">Pengaturan akun dan konter.</p><div class="notice">Owner hanya mengatur data miliknya sendiri.</div></section>`;
if(file==='page.html')return `<section class="card"><h1 class="page-title">${title}</h1><p class="page-sub">Halaman dasar FIXZY.</p></section>`;
return `<section class="card"><h1 class="page-title">${title}</h1><p class="page-sub">${pages[file]?.[1]||''}</p><div class="notice">Owner: <b>${esc(owner)}</b><br>Data halaman ini harus tersaring berdasarkan identitas Owner/Konter. SUPERADMIN dapat membuka halaman untuk pengujian UI, tetapi tidak membaca data bisnis Owner lain.</div><div class="grid"><div class="stat"><small>STATUS</small><strong>Siap</strong></div><div class="stat"><small>SUMBER DATA</small><strong>Firestore</strong></div></div></section>`}
function guard(file,user){if(file==='login.html'||file==='register.html')return true;if(!user){location.href='login.html';return false}if(['dashboard-admin.html','token-reseller.html','daftar-pengguna.html'].includes(file)&&user.role!=='SUPERADMIN'){toast('Halaman khusus SUPERADMIN');setTimeout(()=>location.href='index.html',900);return false}return true}
async function boot(){const file=location.pathname.split('/').pop()||'index.html';if(file==='login.html'){renderLogin();return}if(file==='register.html'){renderRegister();return}onAuthStateChanged(auth,async u=>{const user=u?await currentUser():null;if(!guard(file,user))return;shell(user,pages[file]?.[0]||'FIXZY',pageContent(file,user))});}
function renderLogin(){document.body.innerHTML=`<main><section class="card login-card"><h1>FIXZY</h1><h2>Login akun FIXZY</h2><div class="field"><label>Email</label><input id="email" type="email" autocomplete="username"></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password"></div><button class="btn btn-primary" id="loginBtn" style="width:100%">Masuk</button><p class="muted">Role yang didukung: SUPERADMIN, OWNER, KARYAWAN.</p><a href="register.html">Daftar Owner baru</a></section></main>`;$("loginBtn").onclick=async()=>{const email=$("email").value.trim(),pass=$("password").value;if(!email||!pass)return toast('Email dan password wajib diisi');const b=$("loginBtn");b.disabled=true;b.textContent='Memproses...';try{await signInWithEmailAndPassword(auth,email,pass);location.href='index.html'}catch(e){toast('Login gagal: '+(e.code||e.message))}finally{b.disabled=false;b.textContent='Masuk'}}}
function renderRegister(){document.body.innerHTML=`<main><section class="card login-card"><h1>FIXZY</h1><h2>Daftar Owner baru</h2><div class="field"><label>Nama Owner</label><input id="nama"></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Password</label><input id="password" type="password" minlength="6"></div><button class="btn btn-primary" id="registerBtn" style="width:100%">Daftar</button><p><a href="login.html">Kembali ke login</a></p></section></main>`;$("registerBtn").onclick=async()=>{const nama=$("nama").value.trim(),email=$("email").value.trim(),pass=$("password").value;if(!nama||!email||pass.length<6)return toast('Nama, email, dan password minimal 6 karakter wajib diisi');const b=$("registerBtn");b.disabled=true;b.textContent='Mendaftarkan...';try{const cred=await createUserWithEmailAndPassword(auth,email,pass);await setDoc(doc(db,'users',cred.user.uid),{uid:cred.user.uid,email,ownerEmail:email,ownerUid:cred.user.uid,ownerId:cred.user.uid,konterId:cred.user.uid,nama,displayName:nama,role:'OWNER',createdAt:serverTimestamp()});toast('Pendaftaran berhasil');setTimeout(()=>location.href='index.html',700)}catch(e){toast('Pendaftaran gagal: '+(e.code||e.message))}finally{b.disabled=false;b.textContent='Daftar'}}}
boot();
